server:
  port: 8086
  servlet:
    context-path: /notifications

spring:
  application:
    name: notifications
  # datasource:
  #   url: jdbc:mysql://localhost:3306/notificationsdb
  #   username: root
  #   password: 1234
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  firebase:
    firebase-configuration-file: google/serviceAccountKey.json

  main:
    allow-bean-definition-overriding: true

  cloud:
    gcp:
      security:
        firebase:
          enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.vou.notifications.kafka.deserializer.EventSessionInfoDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

