global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8888' ]
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'discovery-server:8761' ]
  - job_name: 'identity'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'identity:8071' ]
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'users:8081' ]
  - job_name: 'games'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'games:8082' ]
  - job_name: 'sessions'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'sessions:8084' ]

  
