services:
  network-config:
    networks:
      - vou_network

  base-config:
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
      service: network-config

  db-config:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
    extends:
      service: network-config

  discovery-config:
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    extends:
      service: base-config
