CREATE DATABASE IF NOT EXISTS usersdb;
CREATE DATABASE IF NOT EXISTS identitydb;
CREATE DATABASE IF NOT EXISTS gamesdb;
CREATE DATABASE IF NOT EXISTS eventsdb;
CREATE DATABASE IF NOT EXISTS metabasedb;
CREATE DATABASE IF NOT EXISTS notificationsdb;