server:
  port: 8080
spring:
  application:
    name: games
  datasource:
    url: jdbc:mysql://localhost:3306/gamesdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  sql:
  #    init:
  #      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      optional:configserver:http://localhost:8071/