server:
  port: 8080
spring:
  application:
    name: games
  datasource:
    url: jdbc:mysql://localhost:3306/games
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      optional:configserver:http://localhost:8071/