spring:
  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            hind: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
    port: 8081
    servlet:
      context-path: /users
