spring:
  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3306/events_service
    username: root
    password: 1234

  main:
    banner-mode: off

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            hind: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
    port: 8081
